apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  workspaces:
    - name: output
  params:
    - name: repo-url
      default: "https://github.com/TON_COMPTE/ci-cd-final-project.git"
    - name: branch
      default: main
    - name: app-name
      default: hitcounter
    - name: build-image
      default: image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/hitcounter:latest
  tasks:
    - name: cleanup
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: output
    - name: git-clone
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: namespace
            value: openshift-pipelines
      runAfter: [cleanup]
      params:
        - name: URL
          value: $(params.repo-url)
        - name: REVISION
          value: $(params.branch)
      workspaces:
        - name: output
          workspace: output
    - name: flake8
      taskRef:
        name: flake8
      runAfter: [git-clone]
      params:
        - name: image
          value: "python:3.9-slim"
        - name: args
          value: ["--count", "--max-complexity=10", "--max-line-length=127", "--statistics"]
      workspaces:
        - name: source
          workspace: output
    - name: nose
      taskRef:
        name: nose
      runAfter: [flake8]
      params:
        - name: args
          value: "-v --with-spec --spec-color"
      workspaces:
        - name: source
          workspace: output
    - name: buildah
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: buildah
          - name: namespace
            value: openshift-pipelines
      runAfter: [nose]
      params:
        - name: IMAGE
          value: $(params.build-image)
      workspaces:
        - name: source
          workspace: output
    - name: deploy
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: openshift-client
          - name: namespace
            value: openshift-pipelines
      runAfter: [buildah]
      params:
        - name: SCRIPT
          value: |
            oc create deployment $(params.app-name) --image=$(params.build-image) --dry-run=client -o yaml | oc apply -f -
